<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="$results.testClass.xmlTest.name"
           tests="1"
           failures="1"
           errors="0"
           skipped="0"
           time="0.327">
  <properties />
            <testcase name="productInfo on productInfo(com.emma.app.my_rest_test.HttpClientTest)" time="0.327" classname="com.emma.app.my_rest_test.HttpClientTest">
                <failure type="java.lang.AssertionError"
                  message="返回的视频数量不一致 expected [12652] but found [12658]"
              >
<![CDATA[java.lang.AssertionError: 返回的视频数量不一致 expected [12652] but found [12658]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:494)
  org.testng.Assert.assertEquals(Assert.java:123)
  org.testng.Assert.assertEquals(Assert.java:176)
  com.emma.app.my_rest_test.HttpClientTest.productInfo(HttpClientTest.java:65)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
  org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
  org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
  org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
  org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
  org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
  org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
  org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
  org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
  org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
  org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
  org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
  org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
  org.junit.runners.ParentRunner.run(ParentRunner.java:363)
  org.junit.runner.JUnitCore.run(JUnitCore.java:137)
  org.junit.runner.JUnitCore.run(JUnitCore.java:115)
  org.testng.junit.JUnit4TestRunner.start(JUnit4TestRunner.java:81)
  org.testng.junit.JUnit4TestRunner.run(JUnit4TestRunner.java:69)
  org.testng.TestRunner$1.run(TestRunner.java:682)
  org.testng.TestRunner.runWorkers(TestRunner.java:1012)
  org.testng.TestRunner.privateRunJUnit(TestRunner.java:713)
  org.testng.TestRunner.run(TestRunner.java:614)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
  org.testng.TestNG.run(TestNG.java:1031)
  org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:132)
  org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
  org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
  org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:147)
  org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
  org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
  org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
      </failure>

          </testcase>
  
  
  
</testsuite>
